### ISSUE TITLE
Glyph U+1B22C (𛈬)

### ISSUE THREAD

**Issue by sgalal** [LisaHuang2017/noto-sans-nushu#5]
Currently glyph U+1B22C (𛈬) looks a bit wield:

![U+1B22C (𛈬)](https://user-images.githubusercontent.com/32255369/79936090-166f4b80-8489-11ea-9e2e-14a496f402a8.png)

 I think it is better to “go strait”, like in U+1B184 (𛆄):

![U+1B184 (𛆄)](https://user-images.githubusercontent.com/32255369/79936446-1754ad00-848a-11ea-8cae-2a401062e07a.png)

From the Unicode standard:

![U+1B22C (𛈬) in the Unicode standard](https://user-images.githubusercontent.com/32255369/79936595-71557280-848a-11ea-800d-f17994e70baa.png)

**Comment by LisaHuang2017** [comment]
Hi @sgalal , thank you for looking through the character set thoroughly 😊
As you can see in the [PDF](https://github.com/LisaHuang2017/noto-sans-nushu/blob/master/images-process/08-nushu-samples-scans-table.pdf) with scanned samples of as many glyphs as I could find in several documents, I designed every characters in Noto Sans Nüshu so that they would follow the shapes presented as they are in most cases of written texts, rather than follow the references in the Unicode "to the letter". 
<img width="675" alt="Capture d’écran 2020-04-22 à 10 50 45" src="https://user-images.githubusercontent.com/32390132/79961902-9e545600-8487-11ea-9f70-9ebf078c4a83.png">

Also, this is the glyph used to transcribe 书 in Chinese, all over Jiangyong wity there are signs and panels mentioning "江永女书" with this U1B22C, and after showing the character set to Pr Zhao Liming and locals, they all validated the shapes. 

I'm sure there would be improvement on a typeface. Just like type design in Latin, there can be endless corrections and improvements... But I'm confident with this one 

🙃
